---
title: "Relationship Between Working Adults, Their Mental Fatigue Score, and Burn Rate"
description: |
  The transition to the online environment hasn't only affected students, but also adults as well. Data on a sample of 100 adult employees was taken and analyzed. From the variables taken from the experiment, I chose to compare if they could work from home, each of their mental fatigue score, and their burn rate from working. From the graph below, we can conclude that adults that don't have access working from home tend to have more of a burn rate with roughly the same mental fatigue score.
date: "`r Sys.Date()`"
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(tidyverse)
library(lubridate)
library(ggplot2)
library(janitor)
library(ggthemes)
library(data.table)
library(distill)


adult_raw_data <- read_csv("train.csv")
```

```{r, echo= FALSE}


adult_clean_data <- adult_raw_data %>%
  filter(`WFH Setup Available` %in% c("Yes", "No")) %>%
  select(`WFH Setup Available`, `Mental Fatigue Score`, `Burn Rate`) %>%
  group_by(`WFH Setup Available`) %>%
  drop_na() %>%
  head(100)


adult_clean_data %>%
  ggplot(mapping = aes(x= `Mental Fatigue Score`, y =`Burn Rate`)) +
  geom_jitter() +
  facet_wrap(~`WFH Setup Available`) +
  geom_smooth(method = "lm", formula = y~x)

```


^[https://www.kaggle.com/blurredmachine/are-your-employees-burning-out?select=train.csv]



